### ISSUE TITLE
Collaborate with ember-i18n / ember-cli-i18n / ember-intl?

### ISSUE THREAD

**Issue by acorncom** [heathharrelson/ember-i18next#14]
Howdy, just saw your extension show up on EmberAddons.  I'm starting to notice a huge selection of i18n extensions ;-)

Is there any chance you might be able to collaborate with the other extensions that are working on this as well so we don't all duplicate effort?

I opened a similar issue here: https://github.com/yahoo/ember-intl/issues/109 and it looks like we might end up with one super-nice extension if we could all do this jointly ...

Interested in your thoughts ...

**Comment by heathharrelson** [comment]
Hi — I'd be happy to see the Ember community converge on a single widely-accepted solution for i18n. It would definitely ease the path for developers new to Ember if they didn't have to make a choice between multiple competing solutions to every problem, and I think that collaboration and merging of projects will play a role in solving this problem.

That being said, this addon was created to simplify integrating an existing JavaScript i18n library with specific advantages into an Ember app my employer is building right now. At least for the time being, merging with another project would be impracticable, as it would cost us a fair amount in terms of rewriting things.

I entirely understand your concern about the rate that the options are expanding, and I agree that as developers we should look for opportunities to collaborate before reinventing the wheel. I'm just not sure that collaborating is the solution in this specific case.

**Comment by acorncom** [comment]
:+1: Makes sense. Thanks for the info and I'll close this issue now :-)
